### ISSUE TITLE
LDAP support?

### ISSUE THREAD

**Issue by michal0000000** [NUKIB/misp#126]
Hello,
is there any way to implement LDAP/LDAPS auth without bypassing the default MISP login screen and without using basic auth as a substitute ?

The tutorial listed below doesn't work since the `rh-php72-php-ldap` package is unavailable on centos 8. Also the PHP version in this projects image is newer.
https://www.circl.lu/doc/misp/appendices/

Would be really grateful for any help.

**Comment by ondj** [comment]
Hello, sorry, no LDAP support is planned as LDAP is outdated protocol.
