### ISSUE TITLE
Changing the MySQL Password in compose file for Production causes reboot loop for misp container

### ISSUE THREAD

**Issue by Sky-obli-wind** [NUKIB/misp#128]
There are 3 SQL-passwords in the compose file that are set to "password".
If I change them to anything else, even if it's just to "passwordd" or something, the "misp" container gets stuck at restarting (yes I changed all 3 to the same value).
The other containers (redis, sql, modules) seem to boot normally.
Either I'm doing something wrong or "password" is harcoded at some other point.
Changing any other parameter works flawlessly.

**Comment by haavardw** [comment]
I believe that the sql password is not really changed unless you reset the database by e.g. deleting the volumes before restarting the database. Then the misp container will fail to start as it tries a different password than what is set in the sql container.

**Comment by Sky-obli-wind** [comment]
That would make sense, but it also happens on an initial setup / when I delete all containers.

I remove all 4 containers, change the passwords in the compose file and run the compose afterwards. 3 containers start normally, the misp container itself doesn't and the only thing changed were the 3 "password" parameters (all to the same string).

Maybe it's worth to say I use the arm version if it makes any difference?

**Comment by haavardw** [comment]
Deleting the containers is not enough. That's just the running code, not the database data. You also need to delete the volumes linked to the sql container. Take e.g. a look at `docker volume ls | grep mysql`, or do a `docker inspect` on the running sql container to see what volume(s) it has. Then do `docker volume rm <volume>`.

**Comment by Sky-obli-wind** [comment]
Manually deleting the volumes seems to have done the trick ofc. Thx.
