### ISSUE TITLE
Supervisor failing to start zeromq

### ISSUE THREAD

**Issue by mdavis332** [NUKIB/misp#139]
Hi @ondj,

I'm seeing some ZMQ failures that seem related to your commit 8d29c1afa0ea72c33e1f9b8595c9b0415c713128. Supervisor tries to start the [program:zeromq] multiple times and fails each time, leaving it in a FATAL state. 

As best I can tell, [bin/misp_zeromq_start.sh](https://github.com/NUKIB/misp/main/bin/misp_zeromq_start.sh) tries to run a cake admin subcommand, `cake admin createZmqConfig` which doesn't exist. If I try to run it manually I get the help prompt from cake, indicating it's not a real admin subcommand. I can't find any code or docs for it in the main MISP repo either.

Additionally, [Config/config.php](https://github.com/NUKIB/misp/main/Config/config.php) references a MISP plugin setting (`$plugin['ZeroMQ_supervisor_managed'] = true;`) that also doesn't appear to exist. It doesn't show up in the UI of MISP under the plugins section and I can't find reference to that within the MISP codebase. 

Thanks for any light you can shed on this.

**Comment by ondj** [comment]
@mdavis332 Hello, new MISP was releases, so this image should works again with latest stable MISP version.
