### ISSUE TITLE
STIX

### ISSUE THREAD

**Issue by Benni0** [NUKIB/misp#14]
Is STIX intentionally not installed or is the execution of "pip3 install app/files/scripts/misp-stix/" missing in the Dockerfile?

**Comment by ondj** [comment]
Hello, everything required for STIX importing and exporting should be installed. There was just a bug in MISP, that at the diagnostic page it looks like the libraries are missing. But now it looks like this:


![Snímek obrazovky 2022-01-21 v 13 33 52](https://user-images.githubusercontent.com/19149300/150527943-abf15182-337f-4c2a-9a22-8fbf0886c201.png)
 
Do you have any problem with STIX importing or exporting?

**Comment by Benni0** [comment]
Hello, I have to admit, I haven't tried STIX importing and exporting before submitting this issue. Sorry for that.
My assumption came from the missing libraries in the status page. My status page still looks like this:
![image](https://user-images.githubusercontent.com/18324539/150531360-84b9502f-cabf-40b8-bbf0-eb88930d27c3.png)
After executing "pip3 install /var/www/MISP/app/files/scripts/misp-stix/" the status displayed on the diagnostic page is ok.

STIX export seems to work, so it is probably really just a bug in the diagnostics page as you mentioned.
Thank you!

**Comment by ondj** [comment]
You can download latest image, it should be fixed now. Thanks for report!
