### ISSUE TITLE
Image won't build after changes for v2.4.185

### ISSUE THREAD

**Issue by mdavis332** [NUKIB/misp#147]
@ondj if i understand correctly, i think the following lines also need to be tweaked as part of commit c318b44:
 - https://github.com/NUKIB/misp/blob/main/Dockerfile#L93-L94
 - https://github.com/NUKIB/misp/blob/main/docs/CUSTOMIZATION.md?plain=1#L9-L10
 - https://github.com/NUKIB/misp/blob/main/bin/docker-entrypoint.sh#L6

Specifically, I don't the image will build without the Dockerfile change because the path won't yet exist for `chown`. Instead, there will be an error like this: `chown: cannot access '/var/www/MISP/app/files/img/custom': No such file or directory`

**Comment by netops2devops** [comment]
Yes! I am also running into the exact same problem when trying to manually build a docker image. It appears that there are several bugs in the MISP upstream that are breaking remote sync in 2.4.184 and 2.4.185 so I am trying to build an image with .183 

`docker build --build-arg MISP_VERSION=v2.4.183 -t ghcr.io/nukib/misp .`

**Comment by ondj** [comment]
Hello, thanks for reports. I included your fixes in #148, but even without them it should be fine to build container, as it works for us and also here in CI.

Can you please try it again with changes from #148?

**Comment by mdavis332** [comment]
Hi @ondj, the changes look good but the Dockerfile step that runs `/usr/local/bin/misp_install.sh` still fails for me with the following error:

`chown: cannot access '/var/www/MISP/app/files/img/custom': No such file or directory`

It successfully chown's the `/img/orgs` dir right before that though. Looking at the upstream MISP repo, specifically the v2.4.185 branch, the `/img/custom` dir doesn't exist: https://github.com/MISP/MISP/tree/v2.4.185/app/files/img

The v2.4.184 branch (just before they moved the img location) has both directories: https://github.com/MISP/MISP/tree/v2.4.184/app/webroot/img which indicates it was a change that likely broke that line of the misp_install.sh script. In light of that, perhaps we need to file an Issue in the core MISP repo; that, or adjust the misp_install.sh script logic to attempt to create the directory if it doesn't exist. However, I'm not sure how your build pipeline is working given this change...

**Comment by ondj** [comment]
Yes, please try to build against MISP v2.4.186 that was released today.

**Comment by mdavis332** [comment]
Yay, building against v2.4.186 worked the first time! Thanks for the help @ondj.

**Comment by mdavis332** [comment]
oh, I reckon you'll still want to merge #148, though my test with v2.4.186 worked without it.
