### ISSUE TITLE
Docker build fails because of expired GPG key of Vector repo

### ISSUE THREAD

**Issue by ondrejmo** [NUKIB/misp#171]
Docker build on `267bdf3` fails, because GPG key used by Vector.dev repository is expired.

- https://github.com/NUKIB/misp/blob/main/bin/misp_enable_vector.sh#L22
- https://docs.datadoghq.com/agent/guide/linux-key-rotation-2024

**Comment by ondj** [comment]
Fixed, thinks for report.
