### ISSUE TITLE
User ID setting for jobber tasks

### ISSUE THREAD

**Issue by Benni0** [NUKIB/misp#18]
Hi @ondj,

can we add a config variable which defines the user id for jobber tasks (.jobber)?
I have a setup where all users must be authenticated using oidc so i had to delete the initial created admin user.

If this is ok for you, I will implement this and create a pull request.
When not, please let me know if there is another solution.

**Comment by Benni0** [comment]
@ondj, can you please have a look at my changes https://github.com/Benni0/misp/commit/e202411925df589a129c3dee512e1003c1b00a0f? This is how I had implemented this.

When this changes are ok for you, I will create a pull request.

**Comment by ondj** [comment]
@Benni0 Looks great, please send PR here and I will merge it ASAP. Thanks!
