### ISSUE TITLE
OIDC Integration

### ISSUE THREAD

**Issue by scottdermott** [NUKIB/misp#20]
Hi,

Attempting to integrate wit Azure AD and noticed the following are commented out in the misp.conf

```
    #OIDCRemoteUserClaim email
    #OIDCScope "openid email"
```

Looking at the OIDC Apache guides for Azure AD it should be;
```
    OIDCRemoteUserClaim upn
    OIDCScope "openid email"
```

However; once a valid token and email are returned from Azure AD the user is not authenticated with MISP
```
==> /var/log/httpd/access_log <==
172.18.0.1 - redacted@emailaddress.global [04/Feb/2022:10:23:09 +0000] "GET /oauth2callback?code=<redacted>&state=<redacted>&session_state=73387062-014c-4b93-9f97-df0d47598aa0 HTTP/1.1" 302 206 "-"
==> /var/log/httpd/error_log <==
[Fri Feb 04 10:23:25.308737 2022] [authz_core:error] [pid 419:tid 140012225931008] [client 172.18.0.1:39032] AH01631: user redacted@emailaddress.global: authorization failure for "/":
```

I've enabled MISP debug and don't see any errors within the logs.. any idea where i'm going wrong?

**Comment by Benni0** [comment]
Hi @scottdermott,

can you please verify that the role claim with at least the misp_access role is added to the JWT? The role claim must be added at root level.

**Comment by ondj** [comment]
> Hi @scottdermott,
> 
> can you please verify that the role claim with at least the misp_access role is added to the JWT? The role claim must be added at root level.

Thats good point! I will make it configurable and also provide better documentation for OIDC.

**Comment by scottdermott** [comment]
> Hi @scottdermott,
> 
> can you please verify that the role claim with at least the misp_access role is added to the JWT? The role claim must be added at root level. I'm not familiar with Azure AD, but I had the same problem using Keycloak.

Have you got an example? I can see the mapping of roles to an INT. SO the JWT response need to have misp_access defined?

**Comment by Benni0** [comment]
Hi,
here is an example token from my system. I have removed some sections but focus on the roles claim.
`{
  "exp": 1643977365,
  "iat": 1643977305,
  "auth_time": 1643977305,
  "jti": "6c510edf-41ef-4b11-9335-ccad1bfc82fd",
  "iss": "https://xxxxxxx",
  "aud": [
    "master-realm",
    "account"
  ],
  "sub": "6c510edf-41ef-4b11-9335-ccad1bfc82fd",
  "typ": "Bearer",
  "azp": "misp",
  "nonce": "XXXXXXXXXXXXXXXXXX",
  "session_state": "d12d6054-4d06-4f71-8909-54b518d1345f",
  "acr": "0",
  "allowed-origins": [
    "https://xxxx.xxxx.xx"
  ],
  .....,
  "scope": "openid profile email",
  "sid": "d12d6054-4d06-4f71-8909-54b518d1345f",
  "email_verified": false,
  "roles": [
    "misp-admin-access",
    "misp-access"
  ],
  "name": "Firstname Lastname",
  "preferred_username": "user_name",
  "given_name": "Firstname",
  "family_name": "Lastname",
  "email": "user@examle.com"
}`

When you set apaches loglevel to debug in misp.conf (`LogLevel debug`) you can search for `OIDC_CLAIM_roles` in apaches logs.
In my case the log output is:
`oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_roles: misp-admin-access,misp-access", referer:...`
If you don't get this line, the claim is missing.

**Comment by scottdermott** [comment]
@Benni0 Thanks; Figured out the OIDC Claim roles in Azure AD.

New issue; 
https://github.com/MISP/MISP/blob/v2.4.152/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php

The version of this file in your latest image does not reflect anything I can see in the MISP Plugin his for OidcAuthenticate

![image](https://user-images.githubusercontent.com/3798711/152542019-7693a748-3c7f-4ca7-b57a-d8ef45fafa8a.png)

**Comment by ondj** [comment]
@scottdermott Yes, thats problem on image side. I will fix it soon.

**Comment by ondj** [comment]
@scottdermott Please download new image, it should be fixed now.

**Comment by scottdermott** [comment]
@ondj Perfect; Yeah that's solved the issue 👍

**Comment by scottdermott** [comment]
So there is an issue with [JakubOnderka\OpenIDConnectClient->validateStateFromSession()](http://localhost:8080/users/login?code=<redacted>#)

The route after login does not complete and I get this error
![image](https://user-images.githubusercontent.com/3798711/152600395-ca189c3e-a354-465c-a3cb-834703548488.png)

Navigating to http://localhost:8080/users/routeafterlogin after this error works and I'm authenticated, but every time I log out and log back in I get the `State is not set in session` error

**Comment by ondj** [comment]
@scottdermott I think the problem can be with cookie, because current policits for samesite cookie is too strict. Can you please try to change this line in `/var/www/MISP/app/Config/core.php` to 

`'session.cookie_samesite' => 'Lax'`

https://github.com/NUKIB/misp/blob/a730f78495acf2279f606dfc2a5d013ecd8bea61/Config/core.php#L200

**Comment by scottdermott** [comment]
@ondj - Thanks, setting 'session.cookie_samesite' => 'Lax'
Resolves the issue

**Comment by ondj** [comment]
@scottdermott Great! Closing for now.

**Comment by gso-trifork-security** [comment]
@ondj I encountered the same problem, when I tried to setup OIDC with keycloak. Can you try to elaborate a little more why this happens and is it possible to change original docker image, so it works without reconfiguration?

**Comment by Benni0** [comment]
@gso-trifork-security there are two problems in this issue, which of them do you encounter?

**Comment by gso-trifork-security** [comment]
@Benni0 I'm talking about the problem with the too strict cookies @ondj is addressing (https://github.com/NUKIB/misp/issues/20#issuecomment-1030343938)

**Comment by Benni0** [comment]
The PHP config parameter [cookie-samesite](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-samesite) defines in which cases the browser should send the cookie when a site initiates a Cross-Site-Request. When the samesite attribute of an cookie is strict, the cookie will only be sent in a first-party context and not be sent along with requests initiated by third party websites.  Your OIDC Authentication Service could be such an third party website in this context. [Here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) is a good explanation.

You can set the parameter using the PHP_SESSIONS_COOKIE_SAMESITE environment variable, so there are no modifications on the container required.

**Comment by gso-trifork-security** [comment]
@Benni0 Sorry I had not seen it was possible to set the same_site policy with an environment variable
