### ISSUE TITLE
Virustotal Public IP permalink is incorrect.

### ISSUE THREAD

**Issue by bjonescts** [NUKIB/misp#64]
![image](https://user-images.githubusercontent.com/70379785/206798742-92f247ed-ad92-4ec0-974c-81047e156393.png)
![image](https://user-images.githubusercontent.com/70379785/206798791-fa15dd19-4921-4b79-bf11-bf8ed6b897ab.png)

The correct URL is:  https://www.virustotal.com/gui/ip-address/<IP> not https://www.virustotal.com/gui/ip_address/<IP>

Not sure if that's a MISP Module issue or a Virustotal one.

**Comment by ondj** [comment]
Hello, nice catch. But to fix that, please report this issue to https://github.com/MISP/misp-modules repository.
