### ISSUE TITLE
Using a claim other than 'roles' for OIDC

### ISSUE THREAD

**Issue by jamesacris** [NUKIB/misp#72]
Hi,

I'm attempting to use OIDC for authentication on MISP. I understand MISP by [default requires the `roles` claim for role mapping](https://github.com/MISP/MISP/issues/8437#issuecomment-1179372370), but unfortunately the IdP I'm using cannot populate the JWT with a `roles` claim. It instead provides a `groups` claim to achieve the same goal. So far I have set up `misp` and `misp/admin` groups which I intend to map to the `misp-access` and `misp-admin` roles.

Is it possible to use this `groups` claim instead of the roles claim? In what way would I need to customise the image to achieve this? Any support would be greatly appreciated 🙂.

**Comment by jamesacris** [comment]
I noticed this in misp.conf: https://github.com/NUKIB/misp/blob/9c9c9ccf0890d9d8ef7203e8a36ba033246f28e2/misp.conf#L80
```
    #OIDCScope "openid email"
```
Which means that the `profile` scope in OIDC is not being requested - this is the scope that contains both roles and groups.

When I un-comment this line and add `profile`, I get different behaviour. Where before I was met with a "permission denied" page, I now hit a different OIDC error page on login, related to crypto challenge method (a seperate issue which I need to work out with my IdP) but I'd still like to know if there's a way to use groups instead of roles.

**Comment by jamesacris** [comment]
Hi @vba-anssi - thanks for your input, good to hear someone has managed to get it working. Your suggestions are in line with a few thing's I've tried. I will give your exact solution a try to see if I had something wrong. Did you also have to un-comment and change this line in `misp.conf` to require the correct scope in the jwt?
```
#OIDCScope "openid email"
```

Also, could you describe exactly how you changed the `OidcAuth.roles_property` config option in the OidcAuth plugin? I had previously attempted changing the instances where the plugin checked for roles to groups, but this is a much better solution.

**Comment by elenezet** [comment]
Hello everyone,
I am trying to configure misp with oidc. I have a redirection to my IDP, an Ok authentication and a referral to my misp instance. On the other hand I always have "Sorry, you do not have access to this page....".
Do you know which field must contain the idp response to authorize the connection?

**Comment by jamesacris** [comment]
Sorry @elenezet - I can't quite understand what your problem is. Have you changed the config as described in the comment above?

> Replace this [line](https://github.com/NUKIB/misp/blob/9c9c9ccf0890d9d8ef7203e8a36ba033246f28e2/misp.conf#L91) 

> by (for regexp syntax please refer to this [page](https://github.com/zmartzone/mod_auth_openidc/wiki/Authorization)) :
> 
> Require claim "groups~misp*"
> Edit this [section](https://github.com/NUKIB/misp/blob/9c9c9ccf0890d9d8ef7203e8a36ba033246f28e2/Config/config.php#L24-L43) (roles_property field is added according to this [code](https://github.com/MISP/MISP/blob/8a67843035ab40de253506664b3a085fd4675125/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php#L15)) :
> 
> 'roles_property' => 'groups',
> 'role_mapper" => [
> '/misp' => 3, // User
> '/misp/admin' => 1, // Admin
> ],

Additionally, there might be logs in `/var/log/httpd/error_log` that may tell you more about what went wrong.

**Comment by jamesacris** [comment]
@vba-anssi's answer seems to be working for me - closing the issue as that solved my initial problem.

**Comment by elenezet** [comment]
@jamesacris i'have all the time this error  vis CAS6 oidc. I found nothng in logs. I'll try with AD authentification.

Unable to validate ID token claims
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Stack Trace
[APP/Plugin/OidcAuth/Lib/Oidc.php line 22](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [JakubOnderka\OpenIDConnectClient->authenticate()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php line 33](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [Oidc->authenticate()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/AuthComponent.php line 772](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [OidcAuthenticate->authenticate()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Component/AuthComponent.php line 612](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [AuthComponent->identify()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Controller/UsersController.php line 1211](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [AuthComponent->login()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[[internal function]](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [UsersController->login()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php line 499](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [ReflectionMethod->invokeArgs()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 193](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [Controller->invokeAction()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 167](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [Dispatcher->_invoke()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
[APP/webroot/index.php line 99](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#) → [Dispatcher->dispatch()](https://misptux1-r.l.infra.arkea.com/users/login?code=OC-8-d-uH8vUAWRknLFs5OPpnjaicvPlwYn4S&state=5c8VQZfw_ONnIUGjrCHiNA#)
