### ISSUE TITLE
MISP: misp container unable to connect to mysql server while using podman

### ISSUE THREAD

**Issue by ErnestoCubo** [NUKIB/misp#73]
Hi I am using podman for first time but seems familiar with docker, well I am using nukib image in CentOS8, while in docker is all working as needed when I try to launch misp with podman  I get the following error: " INFO: (2003, "Can't connect to MySQL server on 'mysql:3036' ([Errno -2] Name or service not known)")'"

I am using the exact same original image but i don't get thing to work.

When I expose mariadb port I can connect and see the database, but misp module for some reason ins't working.

**Comment by dygland** [comment]
I've not yet tried this with podman myself. but it looks like you're using a non-standard mysql port. is that by design or is it a typo which produce this error? According to your error message you're using port 3036 instead of standard 3306. Might this be the issue?

**Comment by ErnestoCubo** [comment]
Hi, I did some troubleshooting and I solved it by installing podman-plugins, without podman-plugins the containers are unable to comunicate each other.
