### ISSUE TITLE
MISP backup and restore scripts does not work on NUKIB MISP docker version

### ISSUE THREAD

**Issue by tbseznam** [NUKIB/misp#75]
Hello, can you please update scripts for backup and also restore in /var/www/MISP/tools/misp-backup/ ?
In backup script is missing parametr for mysqldump (--column-statistics=0) otherwise it ends with error.
After finished recovery misp webpage show: "Permission Denied". Recovery script showed only:
mysqlshow: Cant connect to local MySQL server through socket /var/lib/mysql/mysql.sock.
    
Can you please give us step by step easy to use manual how to migrate misp database to another instance (e.g. disaster recovery from backups) which is tested on latest NUKIB misp version in docker? 

Thank you

**Comment by tbseznam** [comment]
I figure it out, that in docker-compose can be defined volumes and in mysql section add this:
volumes:
- ./mispDatabaseDir:/var/lib/mysql

After instalation it start to store database files in directory mispDatabaseDir next to docker-compose.yml file.
Hopefully it will help someone.

**Comment by SOC-DBE** [comment]
Hi @tbseznam,

Could you explain the process you did for the backup ? Did you only backuped the volumes directories on the host and then added them on another server ? 

Thanks for your time
