### ISSUE TITLE
Docker Build fails

### ISSUE THREAD

**Issue by Benni0** [NUKIB/misp#81]
Hi @ondj,

the docker build currently fails:
```
#18 18.01 + dnf builddep -y --setopt=tsflags=nodocs --setopt=install_weak_deps=False packaging/rpm/jobber.spec
#18 18.09 No such command: builddep. Please use /usr/bin/dnf --help
#18 18.09 It could be a DNF plugin command, try: "dnf install 'dnf-command(builddep)'"
------
executor failed running [/bin/sh -c bash /build/misp_compile_jobber.sh]: exit code: 1
```

I've fixed this by adding the following line to `/build/misp_compile_jobber.sh` (line 19)

`dnf install -y --setopt=tsflags=nodocs --setopt=install_weak_deps=False 'dnf-command(config-manager)'`

**Comment by Benni0** [comment]
Issue seems to be fixed - could be an issue in the base image

**Comment by Benni0** [comment]
Today I had this issue again.

**Comment by ondj** [comment]
@Benni0 Thanks for report, this should be fixed now in `main` branch.
