### ISSUE TITLE
How are builds triggered?

### ISSUE THREAD

**Issue by dygland** [NUKIB/misp#84]
Hello!

I see that the last build of the image is for MISP version 2.4.168. 2.4.169 has been released and 2.4.170 is most likely released in the coming days.

How is the builds triggered? Could the latest version be built?
Thanks

**Comment by Benni0** [comment]
Hi,
you can build the image with the new version by yourself.
For more information see: [Documentation](https://github.com/NUKIB/misp#image-building)

**Comment by dygland** [comment]
Of course, but we're at an airgapped environment where it is quite the burden to build the image ourselves. It would be beneficial to know how this projects builds are correlating with MISP releases before committing the work needed to set up building internally. (I realise this is quite leechy, sorry bout that).
